source ~/.config/nvim/settings.plugins.vim
source ~/.config/nvim/setting.main.vim
source ~/.config/nvim/settings.plugins.syntax.vim
source ~/.config/nvim/settings.plugins.file.managment.vim
source ~/.config/nvim/settings.plugins.git.vim
source ~/.config/nvim/settings.plugins.outmatch.vim
source ~/.config/nvim/coc.plugin.vim
source ~/.config/nvim/settings.plugins.debug.vim
source ~/.config/nvim/settings.plugins.test.vim
